--1. From the group schema, grant yourself insert, update and delete access ONLY on those tables where you require it. 

--To Grant INSERT, UPDATE, DELETE access on all tables in current schema
SELECT 'GRANT INSERT, UPDATE, DELETE ON '||TABLE_NAME||' TO <USERNAME>;' FROM USER_TABLES;

--To Grant ALL PREVILEGES on one table only in current schema
GRANT ALL ON TYPEOFUSAGE TO nkizyuk;
GRANT ALL ON BILL TO nkizyuk;
GRANT all ON MOBILE_ACCOUNT TO nkizyuk;

--To Grant INSERT, UPDATE, DELETE access on one table only in current schema
GRANT SELECT,INSERT, UPDATE, DELETE ON PHONECUSTOMER TO nkizyuk;
GRANT SELECT,INSERT, UPDATE, DELETE ON SIM_CARD TO nkizyuk;
GRANT SELECT,INSERT, UPDATE, DELETE ON PHONE_STOCK TO nkizyuk;
GRANT SELECT,INSERT, UPDATE, DELETE ON PHONE_STATUS TO nkizyuk;


--2. From your own student schema, POPULATE the group schema tables that are your responsibility. 
DROP TABLE BILL;
DROP TABLE TYPEOFUSAGE;
DROP TABLE MOBILE_ACCOUNT;

CREATE TABLE BILL AS(SELECT *FROM MYPHONE_SERVICE.BILL);
CREATE TABLE TYPEOFUSAGE AS(SELECT *FROM MYPHONE_SERVICE.TYPEOFUSAGE);
CREATE TABLE MOBILE_ACCOUNT AS(SELECT *FROM MYPHONE_SERVICE.MOBILE_ACCOUNT);

--TO CHANGE CONSTTRANT FOR TABLE BILL COLUMN NO_OF_UNITS_USED TO NULL
ALTER TABLE BILL MODIFY(NO_OF_UNITS_USED NUMBER (5) NULL);

/* Insert INFORMATION into table BILL. FOR CUSTOMER WITH ACCOUNT NUMBER: 80087008*/       
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE, TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'14-FEB-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 2);
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE,TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'18-FEB-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 5);
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE,TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'29-FEB-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 6);
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE,TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'13-MAR-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 7);
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE,TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'15-MAR-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 20);
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE,TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'26-MAR-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 9); 
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE,TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'01-APR-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 15);
INSERT INTO BILL(ACCOUNT_NUMBER, DATE_TIME_OF_USAGE,TYPE_OF_USAGE, PHONE_NO_ACCESSED, ACCESS_PROVIDER, NO_OF_UNITS_USED)
       VALUES (80087008,'10-APR-2016','Local Text Message',   '(085)135 5057', ' MyPhone', 30);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'17-FEB-2016','Overseas Text Message','(086)195 5453', ' Tree', 20);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'12-FEB-2016','International Text Message','(0035)096 513 5051', 'UMC', 5);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'04-FEB-2016','Local Phone Call','(085)135 5087', ' MyPhone', 11);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'16-FEB-2016','Local Phone Call','(085)135 9832', ' MyPhone', 3);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'29-FEB-2016','Local Phone Call','(085)135 1023', ' MyPhone', 2);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'05-MAR-2016','Local Phone Call','(085)135 9823', ' MyPhone', 30);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'25-MAR-2016','Local Phone Call','(085)135 8745', ' MyPhone', 18);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'11-APR-2016','Local Phone Call','(085)135 0234', ' MyPhone', 20);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'08-FEB-2016','Overseas Phone Call','(086)195 9845', ' Tree', 15);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'19-FEB-2016','International Phone Call','(0035)096 513 0934','UMC',10);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'05-FEB-2016','Local Data Usage','(085)146 9845', ' MyPhone', 1);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'08-FEB-2016','Local Data Usage','(085)146 0934', ' MyPhone', 1);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'20-FEB-2016','Local Data Usage','(085)146 7564', ' MyPhone', 1);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'07-MAR-2016','Local Data Usage','(085)146 0945', ' MyPhone', 1);
INSERT INTO BILL(ACCOUNT_NUMBER,DATE_TIME_OF_USAGE,TYPE_OF_USAGE,PHONE_NO_ACCESSED,ACCESS_PROVIDER,NO_OF_UNITS_USED) 
       VALUES (80087008,'17-FEB-2016','International Data Usage','(085)146 7654', ' MyPhone', 1);

select*from MOBILE_ACCOUNT;       
INSERT INTO BILL (ACCOUNT_NUMBER,DATE_TIME_OF_USAGE)VALUES((SELECT ACCOUNT_NUMBER FROM MOBILE_ACCOUNT WHERE customer_id = 101),SYSDATE);
       
--I INSERTED INFORMATION INTO TABLE BILL FOR THE REST OF THE CUSTOMERS BUT INSERT STATEMENTS FOR THEM IS NOT INCLUDED HERE

--3. From your own schema, write and run a transaction that would be appropriate to your user role.

--
--NEW TRANSACTION START 
--

/* To UPDATE the START DATE COLUMN FROM BILL TABLE 
AND CHANGE THE SYSTEM DEFUALT DATE TO DATE WHEN CUSTOMERS
CONTRACT WAS STARTED + EVERY TWO MONTH*/
--PL/SQL LOOP AND IF..ELSE CONTROL STATEMENT USED

BEGIN 
    FOR i IN (SELECT CONTRACT_START_DATE, ACCOUNT_NUMBER 
              FROM MYPHONE_SERVICE.PHONECUSTOMER
              FULL OUTER JOIN MOBILE_ACCOUNT USING(CUSTOMER_ID)) 
    LOOP
        IF SYSDATE - i.CONTRACT_START_DATE > 121.68 OR SYSDATE - i.CONTRACT_START_DATE <0
        THEN
            UPDATE BILL SET BILL.START_DATE = i.CONTRACT_START_DATE+(60.84 *((SYSDATE - i.CONTRACT_START_DATE)/60.84)) 
            WHERE ACCOUNT_NUMBER = i.ACCOUNT_NUMBER;
        ELSE
            UPDATE BILL SET BILL.START_DATE = i.CONTRACT_START_DATE
            WHERE ACCOUNT_NUMBER = i.ACCOUNT_NUMBER;
        END IF;
    END LOOP;
END;

--                 
--NEW TRANSACTION START 
--

/* TO INSERT VALUES TO THE BILL.RENEW DATE THE FIRST TIME 
AND TO UPDATE AVERY TWO-MONTH PERIOD THE BILL.RENEW DATE  
THAT IS = BILL START DATE + 60.84(365/12*2); Nataliya Kizyuk*/

UPDATE BILL
      SET BILL.RENEW_DATE = START_DATE + 60.84
      WHERE START_DATE = BILL.START_DATE;
      
/*TO UPDATE AVERY TWO-MONTH PERIOD THE BILL.START DATE*/
UPDATE BILL
      SET BILL.START_DATE = RENEW_DATE
      WHERE RENEW_DATE = BILL.RENEW_DATE AND SYSDATE - RENEW_DATE = 0;


--NEW TRANSACTION START

/* To calculate Total Cost: BILL.Total_Cost =BILL. No_Of Units * TypeOfUsage.Cost_per_unit. Nataliya Kizyuk*/
UPDATE BILL
      SET BILL.TOTAL_COST = NO_OF_UNITS_USED*(SELECT COST_PER_UNIT FROM TYPEOFUSAGE 
      WHERE TYPE_OF_USAGE = BILL.TYPE_OF_USAGE);
      
--      
--NEW TRANSACTION START
--

/* To calculate Billing Amount: BILL.Billing_Amount = SUM OF Total_Cost + Monthly_charge.*/  
--TO UPDATE BILL.BILLING_AMOUNT COLUMN FOR ONE CUSTOMER 
UPDATE BILL
      SET BILL.BILLING_AMOUNT =(SELECT SUM(TOTAL_COST)FROM BILL
      WHERE TOTAL_COST = BILL.TOTAL_COST) +
                              (SELECT Monthly_Charge FROM Mobile_Account
      WHERE ACCOUNT_NUMBER = 80087007); 

--TO UPDATE BILL.BILLING_AMOUNT COLUMN FOR ALL CUSTOMERS IN ONE GO 
--USING TWO DIMENTIONAL ARRAY
--PL/SQL  FOR LOOP AND IF CONTROL STATEMENT USED
 
DECLARE TOTAL NUMBER := 0.00;
BEGIN
    FOR i IN (SELECT ACCOUNT_NUMBER, MONTHLY_CHARGE FROM BILL
              FULL OUTER JOIN MOBILE_ACCOUNT USING(ACCOUNT_NUMBER)) 
    LOOP 
        FOR j IN (SELECT TOTAL_COST,ACCOUNT_NUMBER FROM BILL)
        LOOP
          IF i.ACCOUNT_NUMBER = j.ACCOUNT_NUMBER
          THEN
             TOTAL:= TOTAL + j.TOTAL_COST;
          END IF;
        END LOOP;
        
        UPDATE BILL SET BILL.BILLING_AMOUNT = TOTAL + i.MONTHLY_CHARGE
        WHERE ACCOUNT_NUMBER = i.ACCOUNT_NUMBER;
        TOTAL:= 0;      
    END LOOP;
END;
      
COMMIT;
PURGE RECYCLEBIN;